language: ruby
rvm:
  - 1.9.3
  - 2.2.3
gemfile:
  - gemfiles/activerecord-4.0.gemfile
  - gemfiles/activerecord-4.1.gemfile
  - gemfiles/activerecord-4.2.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
